# MCU settings
MCU_SERIES = f7
CMSIS_MCU = STM32F722xx
MICROPY_FLOAT_IMPL = single
AF_FILE = boards/stm32f722_af.csv
LD_FILES = boards/PYBD_SF2/f722_qspi.ld
TEXT0_ADDR = 0x08008000
TEXT1_ADDR = 0x90000000
TEXT0_SECTIONS = .isr_vector .text .data .ARM
TEXT1_SECTIONS = .text_ext

# MicroPython settings
MICROPY_PY_BLUETOOTH ?= 0
MICROPY_BLUETOOTH_NIMBLE ?= 1
MICROPY_BLUETOOTH_BTSTACK ?= 0
MICROPY_PY_LWIP = 0
MICROPY_PY_NETWORK_CYW43 = 0
MICROPY_PY_USSL = 0
MICROPY_SSL_MBEDTLS = 0
MICROPY_VFS_LFS2 = 0

# PYBD-specific frozen modules
FROZEN_MANIFEST = $(BOARD_DIR)/manifest.py
